// NOT USED IN WIKI, IS OLD CONTENT

These "First steps" for the *OpenShift* solution are specifically something that an **cluster admin** should do. That means, they are only supposed to be done once. These ones include:

== 1. Cluster creation

One of the assets is the link:https://github.com/devonfw/devonfw-shop-floor/blob/master/dsf4openshift/cluster-initial-setup.sh[`cluster-initial-setup.sh`] script. It will perform the following operations:

. Creates the cluster with a link:https://github.com/devonfw/devonfw-shop-floor/blob/master/dsf4openshift/origin/master-config.yaml[specific configuration]
. Creates the *Devonfw* project in the cluster as admin
. Creates building images for Angular and Java
. Using the Angular building image, deploys the *Team Portal* app in the *Devonfw* project

`./cluster-initial-setup.sh`

== 2. Install CICD services

This script is based on the link:https://github.com/OpenShiftDemos/openshift-cd-demo/tree/ocp-3.6[*OpenShift CD demo*], that provides:

* Gogs
* Jenkins
* SonarQube
* Nexus
* DEV and STAGE environments (projects to deploy apps)

This is intended to be addapted to the *devonfw-shop-floor* by changing project's names (always *devonfw*).

The good thing here, is that the script provides not only the installation of all tools, but their integration as well. So, besides the *devonfw integration*, no further configuration should be done.